---

- name: 'Crear grupo jboss'
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - jboss

- name: 'Crear usuario jboss'
  user:
    name: "{{ item.user }}"
    state: present
    comment: "{{ item.comment }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items:
    - { user: 'jboss', comment: 'JBoss', groups: 'jboss' }
