package net.lacnic.elections.domain.pre;

public enum CandidateDeclarationCode {
	INCOMPATIBILITIES_AND_CAPACITIES,
	CONFLICTS_OF_INTEREST,
	COMPETENCIES_AND_SUITABILITY,
	DISCIPLINARY_REGULATION,
	IANA_KNOWLEDGE,
	ASO_KNOWLEDGE,
	PEP_DECLARATION,
	DYNAMIC_COMMITMENTS,
	DATA_USAGE_AND_PUBLICATION
}
