
name: CI

on:
  push:
    branches: [ develop ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean package

      # Share artifacts inside workflow
      - name: Upload actifacts
        uses: actions/upload-artifact@v2
        with:
          name: lacnic-elections-build
          path: |
            pom.xml
            elections-ejb/pom.xml
            elections-ejb/target/elections-ejb.jar
            elections-admin-web/pom.xml
            elections-admin-web/target/elections.war
            elections-services/pom.xml
            elections-services/target/elections-ws.war

  deploy: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download actifacts
        uses: actions/download-artifact@v2
        with:
          name: lacnic-elections-build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_ED25519 }}
          known_hosts: 'placeholder-to-avoid-error'

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.DEMO_HOSTNAME }} >> ~/.ssh/known_hosts

      - name: Copy artifacts to server with rsync
        run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.DEMO_HOSTNAME }}:${{ secrets.DEPLOY_WORK_DIR }}/artifacts/

      - name: Run deploy script
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.DEMO_HOSTNAME }} "${{ secrets.DEPLOY_WORK_DIR }}/deploy.sh >> ${{ secrets.DEPLOY_WORK_DIR }}/deploy.log"
