
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@develop

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean install

      # Share artifacts inside workflow
      - name: Upload actifacts
        uses: actions/upload-artifact@v2
        with:
          name: lacnic-elecciones-build
          path: |
            pom.xml
            elecciones-ejb/pom.xml
            elecciones-ejb/target/elecciones-ejb.jar
            elecciones-admin-web/pom.xml
            elecciones-admin-web/target/elecciones.war
            elecciones-services/pom.xml
            elecciones-services/target/elecciones-ws.war

  deploy: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download previously shared build
      - name: Download actifacts
        uses: actions/download-artifact@v2
        with:
          name: lacnic-elecciones-build

      - name: Build maven settings file
        uses: s4u/maven-settings-action@v2.1.1
        with:
          servers: '[{ "id": "wildfly-elecciones-demo", "username": "${{ secrets.WILDFLY_ADMIN_USER }}", "password": "${{ secrets.WILDFLY_ADMIN_PWD }}" }]'

      - name: Deploy artifacts
        run: mvn wildfly:deploy-only -Dwildfly.id=wildfly-elecciones-demo -Dwildfly.hostname=elecciones-demo.lacnic.net.uy -Dwildfly.port=9898

      #- name: Display structure of downloaded files
      #  run: ls -R
